import { Job } from "./types";

export const JOBS: Job[] = [
  {
    job_id: "JO-2026-012",
    name: "Juan Dela Cruz",
    plate_number: "ABC-1234",
    car_make: "Toyota Fortuner",
    car_color: "White",
    service: "PPF",
    scheduled_start: "Apr 5, 2026, 9:00 AM",
    status: "Pending",
    progress: 0,
    stages_label: "0 of 5 stages",
    stages: [
      { name: "Surface Preparation", status: "pending" },
      { name: "Film Cutting", status: "pending" },
      { name: "Film Application", status: "pending" },
      { name: "Edge Sealing", status: "pending" },
      { name: "Final Inspection", status: "pending" },
    ],
  },
  {
    job_id: "JO-2026-011",
    name: "Maria Garcia",
    plate_number: "DEF-5678",
    car_make: "Honda Civic",
    car_color: "Black",
    service: "Ceramic Coating",
    scheduled_start: "Apr 3, 2026, 9:00 AM",
    status: "Ongoing",
    progress: 75,
    stages_label: "3 of 4 stages",
    stages: [
      { name: "Surface Preparation", status: "completed", timestamp: "Apr 3, 10:15 AM" },
      { name: "Coating Application", status: "completed", timestamp: "Apr 3, 11:30 AM" },
      { name: "Curing Process", status: "active" },
      { name: "Final Inspection", status: "pending" },
    ],
  },
  {
    job_id: "JO-2026-010",
    name: "Ana Reyes",
    plate_number: "GHI-9012",
    car_make: "Mitsubishi Montero",
    car_color: "White",
    service: "Dash Cam Installation",
    scheduled_start: "Apr 1, 2026, 8:30 AM",
    status: "Ongoing",
    progress: 33,
    stages_label: "1 of 3 stages",
    stages: [
      { name: "Unit Inspection", status: "completed", timestamp: "Apr 1, 9:00 AM" },
      { name: "Installation", status: "active" },
      { name: "Testing & Calibration", status: "pending" },
    ],
  },
  {
    job_id: "JO-2026-009",
    name: "Elena Flores",
    plate_number: "STU-5678",
    car_make: "Nissan Navara",
    car_color: "Gray",
    service: "Ceramic Coating",
    scheduled_start: "Mar 31, 2026, 1:00 PM",
    status: "Quality Check",
    progress: 100,
    stages_label: "4 of 4 stages",
    stages: [
      { name: "Surface Preparation", status: "completed", timestamp: "Mar 31, 2:00 PM" },
      { name: "Coating Application", status: "completed", timestamp: "Mar 31, 3:30 PM" },
      { name: "Curing Process", status: "completed", timestamp: "Apr 1, 9:00 AM" },
      { name: "Final Inspection", status: "completed", timestamp: "Apr 1, 11:00 AM" },
    ],
  },
  {
    job_id: "JO-2026-008",
    name: "Carlos Santos",
    plate_number: "JKL-3456",
    car_make: "Ford Ranger",
    car_color: "Blue",
    service: "Interior Detailing",
    scheduled_start: "Mar 30, 2026, 10:00 AM",
    status: "Completed",
    progress: 100,
    stages_label: "3 of 3 stages",
    stages: [
      { name: "Interior Vacuum", status: "completed", timestamp: "Mar 30, 10:30 AM" },
      { name: "Deep Clean", status: "completed", timestamp: "Mar 30, 12:00 PM" },
      { name: "Final Polish", status: "completed", timestamp: "Mar 30, 2:00 PM" },
    ],
  },
  {
    job_id: "JO-2026-007",
    name: "Liza Mendoza",
    plate_number: "MNO-7890",
    car_make: "Hyundai Tucson",
    car_color: "Silver",
    service: "Paint Correction",
    scheduled_start: "Mar 29, 2026, 11:30 AM",
    status: "Delayed",
    progress: 60,
    stages_label: "2 of 4 stages",
    stages: [
      { name: "Paint Assessment", status: "completed", timestamp: "Mar 29, 11:45 AM" },
      { name: "Clay Bar Treatment", status: "completed", timestamp: "Mar 29, 1:00 PM" },
      { name: "Machine Polishing", status: "active" },
      { name: "Paint Sealant", status: "pending" },
    ],
  },
  {
    job_id: "JO-2026-006",
    name: "Mark Bautista",
    plate_number: "PQR-1122",
    car_make: "Kia Sportage",
    car_color: "Black",
    service: "Ceramic Coating",
    scheduled_start: "Mar 28, 2026, 2:00 PM",
    status: "Cancelled",
    progress: 40,
    stages_label: "1 of 4 stages",
    stages: [
      { name: "Surface Preparation", status: "completed", timestamp: "Mar 28, 2:15 PM" },
      { name: "Coating Application", status: "pending" },
      { name: "Curing Process", status: "pending" },
      { name: "Final Inspection", status: "pending" },
    ],
  },
  {
    job_id: "JO-2026-005",
    name: "Angela Cruz",
    plate_number: "VWX-3344",
    car_make: "Mazda CX-5",
    car_color: "Red",
    service: "PPF",
    scheduled_start: "Mar 27, 2026, 9:00 AM",
    status: "Released",
    progress: 100,
    stages_label: "5 of 5 stages",
    stages: [
      { name: "Surface Preparation", status: "completed", timestamp: "Mar 27, 9:30 AM" },
      { name: "Film Cutting", status: "completed", timestamp: "Mar 27, 11:00 AM" },
      { name: "Film Application", status: "completed", timestamp: "Mar 27, 1:00 PM" },
      { name: "Edge Sealing", status: "completed", timestamp: "Mar 27, 3:00 PM" },
      { name: "Final Inspection", status: "completed", timestamp: "Mar 27, 4:30 PM" },
    ],
  },
];
