import { HeadTechJob } from "./types";

export const ACTIVE_JOBS: HeadTechJob[] = [
  {
    job_id: "JO-2026-011",
    customer_name: "Maria Garcia",
    plate_number: "DEF-5678",
    car_make: "Honda Civic",
    car_color: "Black",
    service: "Ceramic Coating",
    technician_name: "Pedro Lim",
    scheduled_start: "Apr 3, 2026, 9:00 AM",
    status: "Ongoing",
    progress: 60,
    stage_groups: [],
    has_delayed_stage: false,
  },
  {
    job_id: "JO-2026-010",
    customer_name: "Carlos Rivera",
    plate_number: "GHI-9012",
    car_make: "Ford Ranger",
    car_color: "Silver",
    service: "Window Tinting",
    technician_name: "Rosa Aquino",
    scheduled_start: "Apr 2, 2026, 10:00 AM",
    status: "For Release",
    progress: 100,
    stage_groups: [],
    has_delayed_stage: false,
  },
  {
    job_id: "JO-2026-009",
    customer_name: "Ana Reyes",
    plate_number: "JKL-3456",
    car_make: "Mitsubishi Montero",
    car_color: "White",
    service: "Dash Cam Installation",
    technician_name: "Mark Santos",
    scheduled_start: "Apr 1, 2026, 8:30 AM",
    status: "Ongoing",
    progress: 33,
    stage_groups: [],
    has_delayed_stage: false,
  },
  {
    job_id: "JO-2026-006",
    customer_name: "Elena Flores",
    plate_number: "STU-5678",
    car_make: "Nissan Navara",
    car_color: "Gray",
    service: "Ceramic Coating",
    technician_name: "David Cruz",
    scheduled_start: "Mar 31, 2026, 1:00 PM",
    status: "For Release",
    progress: 100,
    stage_groups: [],
    has_delayed_stage: false,
  },
  {
    job_id: "JO-2026-005",
    customer_name: "Juan Dela Cruz",
    plate_number: "ABC-1234",
    car_make: "Toyota Fortuner",
    car_color: "White",
    service: "PPF",
    technician_name: "Pedro Lim",
    scheduled_start: "Mar 30, 2026, 9:00 AM",
    status: "Pending",
    progress: 0,
    stage_groups: [],
    has_delayed_stage: false,
  },
  {
    job_id: "JO-2026-004",
    customer_name: "Liza Mendoza",
    plate_number: "MNO-7890",
    car_make: "Hyundai Tucson",
    car_color: "Silver",
    service: "Paint Correction",
    technician_name: "Rosa Aquino",
    scheduled_start: "Mar 29, 2026, 11:30 AM",
    status: "Delayed",
    progress: 60,
    stage_groups: [],
    has_delayed_stage: false,
  },
];

export const TECHNICIANS = [
  "Pedro Lim",
  "Rosa Aquino",
  "Mark Santos",
  "David Cruz",
];
