-- Create the Messenger conversation/message tables.

-- These tables were referenced by the messenger webhook code and types
-- (types/supabase.ts) but were never actually created in the database. Every
-- webhook call failed with "Could not find the table
-- 'public.messenger_conversation' in the schema cache", so the AI chatbot
-- could not run. `inquiry` already exists and is intentionally untouched.

CREATE TABLE IF NOT EXISTS public.messenger_conversation (
  conversation_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  psid                text,
  customer_name       text,
  status              text NOT NULL DEFAULT 'open',   -- open | pending | closed
  is_vehicle_inquiry  boolean NOT NULL DEFAULT false,
  handler_role        text,                            -- sales | admin
  handled_by_user_id  uuid,
  last_message_at     timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.messenger_message (
  message_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id  bigint NOT NULL REFERENCES public.messenger_conversation(conversation_id)
                     ON DELETE CASCADE,
  sender_type      text NOT NULL,                      -- customer | agent
  message_body     text NOT NULL,
  sent_at          timestamptz NOT NULL DEFAULT now(),
  fb_message_id    text,
  sent_by_user_id  uuid
);

CREATE INDEX IF NOT EXISTS idx_messenger_conversation_psid
  ON public.messenger_conversation (psid);

CREATE INDEX IF NOT EXISTS idx_messenger_message_conversation
  ON public.messenger_message (conversation_id, sent_at);

-- Refresh the PostgREST schema cache so existing webhook requests stop failing
-- with the "Could not find the table ... in the schema cache" error immediately.
NOTIFY pgrst, 'reload schema';